### ISSUE TITLE
Python 3.10 not supported

### ISSUE THREAD

**Issue by set-soft** [Technologicat/mcpyrate#29]
Python 3.10 modified the `alias` attributes.

For more information: INTI-CMNB/KiBot#128

**Comment by Technologicat** [comment]
Thank you for the heads-up!

**Comment by Technologicat** [comment]
Fixed along the lines of what was suggested by @brathis (but using `ast.copy_location`).

I don't have a 3.10 environment myself yet, but I updated the CI setup, and GitHub says the tests pass. :)

@set-soft, could you confirm if it works for you?

**Comment by Technologicat** [comment]
Tested by @brathis at https://github.com/INTI-CMNB/KiBot/issues/128, and confirmed working.

The fix will be included in `mcpyrate` 3.6.0.
