### ISSUE TITLE
Suggestion: remove distutils dependency

### ISSUE THREAD

**Issue by set-soft** [Technologicat/mcpyrate#33]
The following code uses distutils:

https://github.com/Technologicat/mcpyrate/blob/0af4362123e11d663d3dcf2c88e6e987fb350c0f/mcpyrate/importer.py#L88

The distutils module is deprecated and will go away in 3.12.
Additionally, it isn't part of the Debian Python package, you must install a dependency (`python3-distutils`).

What about the following?:

```python
stdlib_dir = os.path.dirname(os.__file__)
```

I think is safe to assume that the `os` module comes from the standard lib.

**Comment by Technologicat** [comment]
Yes, sounds reasonable.

Let's change this in the next version.

(Sorry I missed this earlier - I've been away from `mcpyrate` for a while.)

**Comment by Technologicat** [comment]
Fixed in 3.6.1, now available on PyPI. Thanks!
